# Generated by Django 2.2 on 2020-08-21 09:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume',
            new_name='Vacancy',
        ),
    ]
